apiVersion: apps/v1
kind: Deployment
metadata:
  name: boiko-hw24-deployment
  labels:
    app: boiko-hw24-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: boiko-hw24-app
  template:
    metadata:
      labels:
        app: boiko-hw24-app
    spec:
      containers:
        - name: boiko-hw24-app-container
          image: akyna/hw_24:1.0.3
          ports:
            - containerPort: 8082
