global:
  resolve_timeout: 5m

route:
  group_by: [ 'alertname' ]
  receiver: 'telegram'
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 5m

receivers:
  - name: 'telegram'
    telegram_configs:
      - bot_token: "YOUR_TELEGRAM_BOT_TOKEN"
        chat_id: "YOUR_TELEGRAM_CHAT_ID"
        message: '{{ template "telegram.default" . }}'

templates:
  - '/etc/alertmanager/templates/telegram.tmpl'
