name: dan-it_step_project_2

services:
  server:
    build:
      context: ./server
    image: ${COMPOSE_PROJECT_NAME}_server:1.0.1
    container_name: ${COMPOSE_PROJECT_NAME}_server
    hostname: ${COMPOSE_PROJECT_NAME}_server
    user: "${UID}:${GID}" # Not need on Mac laptop
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
    networks:
      _network:

  worker:
    privileged: true # Not need on Mac laptop
    user: "${UID}:${GID}" # Not need on Mac laptop
    build:
      context: ./worker
    image: ${COMPOSE_PROJECT_NAME}_worker:1.0.1
    container_name: ${COMPOSE_PROJECT_NAME}_worker
    hostname: ${COMPOSE_PROJECT_NAME}_worker
    # user: jenkins # TODO: discuss
    environment:
      JENKINS_SECRET: 8b755d11281e494db867e9979602eb0307b6830013e739bef1f0ee80492ab833
      JENKINS_AGENT_WORKDIR: /var/lib/jenkins
      JENKINS_URL: http://server:8080/
      JENKINS_AGENT_NAME: worker
    volumes:
      - ./jenkins_worker:/var/lib/jenkins
      - /var/run/docker.sock:/var/run/docker.sock # Only possible on Ubuntu
      - /usr/bin/docker:/usr/bin/docker:ro # Only possible on Ubuntu
      - /usr/libexec/docker/cli-plugins:/usr/libexec/docker/cli-plugins # Only possible on Ubuntu
    depends_on:
      - server
    networks:
      _network:

networks:
  _network:
